corrected

diff --git a/.github/workflows/test-test.yml b/.github/workflows/test-test.yml
--- a/.github/workflows/test-test.yml
+++ b/.github/workflows/test-test.yml
@@ -1,60 +1,34 @@
-name: Test WasmEdge Core
-
-concurrency:
-  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
-  cancel-in-progress: true
+name: Build on MacOS test version
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - master
-    paths:
-      - ".github/workflows/build.yml"
-      - ".github/workflows/reusable-build-on-**"
-      - ".github/workflows/reusable-call-linter.yml"
-      - ".github/workflows/reusable-create-source-tarball.yml"
-      - "include/**"
-      - "lib/**"
-      - "test/**"
-      - "!test/plugins/**"
-      - "thirdparty/**"
-      - "tools/**"
-      - "CMakeLists.txt"
-      - "cmake/**"
-  pull_request:
-    branches:
-      - master
-      - "proposal/**"
-    paths:
-      - ".github/workflows/build.yml"
-      - ".github/workflows/reusable-build-on-**"
-      - ".github/workflows/reusable-call-linter.yml"
-      - ".github/workflows/reusable-create-source-tarball.yml"
-      - "include/**"
-      - "lib/**"
-      - "test/**"
-      - "!test/plugins/**"
-      - "thirdparty/**"
-      - "tools/**"
-      - "CMakeLists.txt"
-      - "cmake/**"
+  workflow_call:
+    inputs:
+      version:
+        type: string
+        required: true
+      matrix: # [ { name, runner, darwin_version }, ... ]
+        type: string
+        required: true
+      release:
+        type: boolean
 
 permissions:
   contents: read
 
 jobs:
-  # TODO: Refactor `lint` with `on.workflow_run`
-  # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
-  lint:
-    uses: ./.github/workflows/reusable-call-linter.yml
-
-  get_version:
-    needs: lint
-    name: Retrieve version information
-    runs-on: ubuntu-latest
-    outputs:
-      version: ${{ steps.prep.outputs.version }}
+  build_on_macos:
+    permissions:
+      contents: write
+    strategy:
+      fail-fast: false
+      matrix:
+        include: ${{ fromJSON(inputs.matrix) }}
+    name: ${{ matrix.name }}
+    runs-on: ${{ matrix.runner }}
+    env:
+      BUILD_TESTS: ON
+      BUILD_TYPE: Debug
     steps:
       - uses: actions/checkout@v4
         with:
@@ -62,121 +36,78 @@ jobs:
       - name: Ensure git safe directory
         run: |
           git config --global --add safe.directory $(pwd)
-      - name: Get version
-        id: prep
+      - name: Setup build environment - non-release
+        if: ${{ !inputs.release }}
         run: |
-          # Retrieve annotated tags. Details: https://github.com/actions/checkout/issues/290
-          git fetch --tags --force
-          echo "Set version: $(git describe --match '[0-9].[0-9]*' --tag)"
-          echo "version=$(git describe --match '[0-9].[0-9]*' --tag)" >> $GITHUB_OUTPUT
+          eval $(/opt/homebrew/bin/brew shellenv)
+          brew install llvm@18 ninja wabt grpc
+      - name: Setup build environment - release
+        if: ${{ inputs.release }}
+        run: |
+          eval $(/opt/homebrew/bin/brew shellenv)
+          brew install llvm@18 ninja wabt
+      - name: Set environment variables for release
+        if: ${{ inputs.release }}
+        run: |
+          echo "BUILD_TESTS=OFF" | tee -a $GITHUB_ENV
+          echo "BUILD_TYPE=Release" | tee -a $GITHUB_ENV
+      - name: Build WasmEdge
+        run: |
+          eval $(/opt/homebrew/bin/brew shellenv)
+          export LLVM_DIR="$(brew --prefix)/opt/llvm@18/lib/cmake"
+          export CC=clang
+          export CXX=clang++
+          rm -rf build output
+          mkdir -p output
+          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWASMEDGE_BUILD_TESTS=$BUILD_TESTS -DWASMEDGE_LINK_LLVM_STATIC=ON -DWASMEDGE_BUILD_PACKAGE="TGZ" -DCMAKE_INSTALL_PREFIX:PATH=$GITHUB_WORKSPACE/output .
+          cmake --build build
+      - name: Test WasmEdge
+        run: |
+          eval $(/opt/homebrew/bin/brew shellenv)
+          export DYLD_LIBRARY_PATH="$(pwd)/build/lib/api:$DYLD_LIBRARY_PATH"
+          cd build
+          ctest
+          cd -
+          nm -g ./build/lib/api/libwasmedge.dylib > libwasmedge.txt
+          awk '{if ($2 == "T" || $2 == "D") print $3}' libwasmedge.txt > file && mv file libwasmedge.txt
+          bash ./.github/scripts/check-symbols.sh
+      - name: Create package tarball
+        run: |
+          eval $(/opt/homebrew/bin/brew shellenv)
+          cmake --build build --target package
+      - name: Test Standalone WasmEdge without LLVM
+        run: |
+          eval $(/opt/homebrew/bin/brew shellenv)
+          export DYLD_LIBRARY_PATH="$(pwd)/build/lib/api:$DYLD_LIBRARY_PATH"
+          echo "otool -L ./build/tools/wasmedge/wasmedge:"
+          otool -L ./build/tools/wasmedge/wasmedge
+          echo "otool -L ./build/tools/wasmedge/wasmedgec:"
+          otool -L ./build/tools/wasmedge/wasmedgec
+          echo "otool -L ./build/lib/api/libwasmedge.dylib:"
+          otool -L ./build/lib/api/libwasmedge.dylib
+          if otool -L ./build/lib/api/libwasmedge.dylib | grep libLLVM; then echo "Fail: libLLVM shared library linked" && exit 1; else echo "Pass: libLLVM shared library not linked"; fi;
 
-  create_source_tarball:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Source Tarball
-    uses: ./.github/workflows/reusable-create-source-tarball.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-
-  build_on_macos:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: macOS
-    uses: ./.github/workflows/reusable-build-on-macos.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-      matrix: "[{'name':'MacOS 13 (x86_64)','runner':'macos-13','darwin_version':22,'arch':'x86_64'},
-                {'name':'MacOS 14 (arm64)','runner':'macos-14','darwin_version':23,'arch':'arm64'}]"
-
-  build_on_manylinux_2_28:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Manylinux_2_28
-    uses: ./.github/workflows/reusable-build-on-manylinux.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-      matrix: "[{'name':'manylinux_2_28 x86_64','runner':'ubuntu-latest','docker_tag':'manylinux_2_28_x86_64','asset_tag':'manylinux_2_28_x86_64'},
-                {'name':'manylinux_2_28 aarch64','runner':'linux-arm64-v2','docker_tag':'manylinux_2_28_aarch64','asset_tag':'manylinux_2_28_aarch64'}]"
-
-  build_on_debian_static:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Debian (static)
-    uses: ./.github/workflows/reusable-build-on-debian-static.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-
-  build_on_alpine_static:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Alpine (static)
-    uses: ./.github/workflows/reusable-build-on-alpine-static.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-
-  build_on_ubuntu:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Ubuntu
-    uses: ./.github/workflows/reusable-build-on-ubuntu.yml
-    secrets: inherit
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-      matrix: "[{'name':'ubuntu-24.04','arch':'x86_64','runner':'ubuntu-latest','compiler':'g++','build_type':'Debug','docker_tag':'ubuntu-24.04-build-gcc','tests':true},
-                {'name':'ubuntu-24.04','arch':'x86_64','runner':'ubuntu-latest','compiler':'g++','build_type':'Release','docker_tag':'ubuntu-24.04-build-gcc','tests':true},
-                {'name':'ubuntu-24.04','arch':'x86_64','runner':'ubuntu-latest','compiler':'clang++','build_type':'Debug','docker_tag':'ubuntu-24.04-build-clang','tests':true},
-                {'name':'ubuntu-24.04','arch':'x86_64','runner':'ubuntu-latest','compiler':'clang++','build_type':'Release','docker_tag':'ubuntu-24.04-build-clang','tests':true},
-                {'name':'ubuntu-20.04','arch':'aarch64','runner':'linux-arm64-v2','compiler':'clang++','build_type':'Release','docker_tag':'ubuntu-20.04-build-clang-aarch64','tests':true},
-                {'name':'linux-static','arch':'x86_64','runner':'ubuntu-latest','compiler':'clang++','build_type':'Release','docker_tag':'ubuntu-24.04-build-clang','options':'-DWASMEDGE_BUILD_SHARED_LIB=Off -DWASMEDGE_BUILD_STATIC_LIB=On -DWASMEDGE_LINK_TOOLS_STATIC=On -DWASMEDGE_BUILD_PLUGINS=Off'},
-                {'name':'ubuntu-22.04-coverage','arch':'x86_64','runner':'ubuntu-latest','compiler':'g++','build_type':'Debug','docker_tag':'ubuntu-22.04-build-gcc','coverage':true,'tests':true}]"
-
-  build_on_windows:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Windows
-    uses: ./.github/workflows/reusable-build-on-windows.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-
-  build_on_windows_msvc:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Windows-MSVC
-    uses: ./.github/workflows/reusable-build-on-windows-msvc.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-
-  build_on_android:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Android
-    uses: ./.github/workflows/reusable-build-on-android.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-
-  build_on_fedora:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Fedora
-    uses: ./.github/workflows/reusable-build-on-fedora.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
-
-  build_on_debian:
-    permissions:
-      contents: write
-    needs: [get_version, lint]
-    name: Debian
-    uses: ./.github/workflows/reusable-build-on-debian.yml
-    with:
-      version: ${{ needs.get_version.outputs.version }}
+          echo "Generate fibonacci.wasm from fibonacci.wat"
+          wat2wasm examples/wasm/fibonacci.wat -o examples/wasm/fibonacci.wasm
+          echo "./build/tools/wasmedge/wasmedgec examples/wasm/fibonacci.wasm fib_c.dylib"
+          ./build/tools/wasmedge/wasmedgec examples/wasm/fibonacci.wasm fib_c.dylib
+          echo "./build/tools/wasmedge/wasmedge --reactor fib_c.dylib fib 20"
+          ./build/tools/wasmedge/wasmedge --reactor fib_c.dylib fib 20
+          echo "./build/tools/wasmedge/wasmedge compile examples/wasm/fibonacci.wasm fib_compile.dylib"
+          ./build/tools/wasmedge/wasmedge compile examples/wasm/fibonacci.wasm fib_compile.dylib
+          echo "./build/tools/wasmedge/wasmedge --reactor fib_compile.dylib fib 20"
+          ./build/tools/wasmedge/wasmedge --reactor fib_compile.dylib fib 20
+      - name: Upload artifact
+        if: ${{ !inputs.release }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: WasmEdge-${{ inputs.version }}-darwin_${{ matrix.darwin_version }}_${{ matrix.arch }}.tar.gz
+          path: build/WasmEdge-${{ inputs.version }}-Darwin.tar.gz
+      - name: Upload package tarball
+        if: ${{ inputs.release }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          eval $(/opt/homebrew/bin/brew shellenv)
+          mv build/WasmEdge-${{ inputs.version }}-Darwin.tar.gz WasmEdge-${{ inputs.version }}-darwin_${{ matrix.arch }}.tar.gz
+          gh release upload ${{ inputs.version }} WasmEdge-${{ inputs.version }}-darwin_${{ matrix.arch }}.tar.gz --clobber
